Feature
Ak0706/review_trial pull request #2
Opened 2021-06-02 16:44 UTC by Ak0706

## Adding Trial project to development branch
The trial project was added to the development branch for reviewing.
The following was done:
- index.html file added
- style.css file added
- Linters added

2021-06-02 17:03 UTC, Ak0706 reviewed
Good job so far!
There are some issues that you still need to work on, but you are almost there!
PLease check the comments.

2021-06-02 17:03 UTC, Ak0706 commented on index.html
> -                        <select id="dropdown" class="form-control" style="width: 100% ;" name="Current Role" required>
Duplicate names found. Please change one of them.

2021-06-02 22:44 UTC, Spayco requested changes
Hi @Ak0706, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-02 22:44 UTC, Spayco commented on index.html
> -                        LAST NAME: <br><input type="text" id="last name" class="form-control" name="last name"
- kindly phrase the comments politely, as suggestions instead of orders. For example:
  * This is a polite suggestion: *"I think it would be better to use semantic tags"*
  * This reads as an order: *"Use semantic tags"*
- please include an explanation, a "why", for each requested change. For example:
  * This is a well explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
  * This request lacks a "why": *Why don't you use an article tag here instead of a div?*

2021-06-02 22:44 UTC, Spayco commented on index.html
> -                        <select id="dropdown" class="form-control" style="width: 100% ;" name="Current Role" required>
same point for this comment too!

2021-06-03 10:25 UTC, Ak0706 commented on index.html
> -                        LAST NAME: <br><input type="text" id="last name" class="form-control" name="last name"
I think the best practice is not to leave spaces between 2 words.

2021-06-03 10:29 UTC, Ak0706 commented on index.html
> -                        <select id="dropdown" class="form-control" style="width: 100% ;" name="Current Role" required>
I think it is best not to repeat ID names.

2021-06-03 10:34 UTC, Ak0706 reviewed
Congratulations @Ak0706 🎉 🥂

Thank you for carefully implementing the required changes._

Your project is complete! 

Comment:
Kindly see the comments for some improvements.

2021-06-03 13:38 UTC, Spayco requested changes
Hi @Ak0706, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 13:38 UTC, Spayco commented on index.html
> -                        LAST NAME: <br><input type="text" id="last name" class="form-control" name="last name"
you've done well with making the comment polite, but I think it still lacks the "why" for the change

2021-06-03 13:38 UTC, Spayco commented on index.html
> -                        <select id="dropdown" class="form-control" style="width: 100% ;" name="Current Role" required>
you've done well with making the comment polite, but I think it still lacks the "why" for the change here too

2021-06-03 13:48 UTC, Ak0706 commented on index.html
> -                        LAST NAME: <br><input type="text" id="last name" class="form-control" name="last name"
I think the best practice is not to leave spaces between 2 words, because browsers treat non-conforming IDs that contain whitespace as if the whitespace is part of the ID.

2021-06-03 13:53 UTC, Ak0706 reviewed
Good job!
You've done well implementing the requested changes.

2021-06-03 13:53 UTC, Ak0706 commented on index.html
> -                        <select id="dropdown" class="form-control" style="width: 100% ;" name="Current Role" required>
I think it is best not to repeat ID names. 
Using duplicate id attribute values is invalid HTML, as HTML specification clearly states that attributes must be unique. Practically, most browsers can handle duplicate ids, but theoretically, they can cause issues if the JavaScript is parsing or calling DOM elements based on these id values.

2021-06-03 14:23 UTC, christianotieno approved these changes
Hi @Ak0706, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 14:28 UTC, merged

2021-06-03 14:34 UTC, Ak0706 commented
Thank you very much.
By the way, I wanted to ask:
What is PR and what is TSE?

Regards,
Akhtar

On Thu, Jun 3, 2021 at 6:23 PM Christian Otieno ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @Ak0706 <https://github.com/Ak0706>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> only 3 code reviews per project. If you think that the code review was not
> fair, you can request a second opinion using this form
> <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Ak0706/review_trial/pull/2#pullrequestreview-675340243>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ3MIZOWITTDN44DY5P6CV3TQ6F7JANCNFSM457DL73Q>
> .
>